BEGIN;
CREATE TABLE commercial.subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES platform.tenants(id),
  source_contract_id uuid NOT NULL, source_contract_revision_number bigint NOT NULL CHECK(source_contract_revision_number>0),
  customer_id uuid NOT NULL, owner_membership_id uuid NOT NULL, created_by_membership_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','PENDING_ACTIVATION','ACTIVE','SUSPENDED','CANCELLED','TERMINATED')),
  effective_from timestamptz NOT NULL, effective_until timestamptz,
  revision_number bigint NOT NULL DEFAULT 1 CHECK(revision_number>0), version bigint NOT NULL DEFAULT 1 CHECK(version>0),
  created_by uuid NOT NULL REFERENCES platform.users(id), updated_by uuid NOT NULL REFERENCES platform.users(id),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE(id,tenant_id), UNIQUE(tenant_id,source_contract_id),
  FOREIGN KEY(source_contract_id,tenant_id) REFERENCES commercial.contracts(id,tenant_id),
  FOREIGN KEY(customer_id,tenant_id) REFERENCES commercial.customers(id,tenant_id),
  FOREIGN KEY(owner_membership_id,tenant_id) REFERENCES platform.memberships(id,tenant_id),
  FOREIGN KEY(created_by_membership_id,tenant_id) REFERENCES platform.memberships(id,tenant_id),
  CHECK(effective_until IS NULL OR effective_until > effective_from)
);
CREATE INDEX subscriptions_tenant_list_idx ON commercial.subscriptions(tenant_id,id);
CREATE TABLE commercial.subscription_plan_origins (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subscription_id uuid NOT NULL, tenant_id uuid NOT NULL REFERENCES platform.tenants(id),
 source_contract_line_item_id uuid NOT NULL, plan_id uuid NOT NULL, plan_name_snapshot text NOT NULL, description_snapshot text NOT NULL DEFAULT '', quantity numeric(19,4) NOT NULL CHECK(quantity>0),
 UNIQUE(subscription_id,source_contract_line_item_id), FOREIGN KEY(subscription_id,tenant_id) REFERENCES commercial.subscriptions(id,tenant_id) ON DELETE RESTRICT
);
CREATE TABLE commercial.subscription_revisions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subscription_id uuid NOT NULL, tenant_id uuid NOT NULL REFERENCES platform.tenants(id), revision_number bigint NOT NULL,
 source_contract_id uuid NOT NULL, source_contract_revision_number bigint NOT NULL, customer_id uuid NOT NULL, owner_membership_id uuid NOT NULL, status text NOT NULL,
 effective_from timestamptz NOT NULL, effective_until timestamptz, snapshot_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(subscription_id,revision_number), FOREIGN KEY(subscription_id,tenant_id) REFERENCES commercial.subscriptions(id,tenant_id) ON DELETE RESTRICT
);
CREATE TABLE commercial.subscription_operations (tenant_id uuid NOT NULL REFERENCES platform.tenants(id), idempotency_key uuid NOT NULL, actor_user_id uuid NOT NULL REFERENCES platform.users(id), operation text NOT NULL, resource_id uuid NOT NULL, request_hash text NOT NULL CHECK(request_hash~'^[0-9a-f]{64}$'), result jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(tenant_id,idempotency_key));
INSERT INTO platform.permissions(permission_key,description) VALUES
 ('commercial.subscription.read','Read tenant-scoped subscriptions'),('commercial.subscription.create','Create subscriptions from active contracts'),('commercial.subscription.update','Update subscription drafts'),('commercial.subscription.assign','Assign subscription owners'),('commercial.subscription.request_activation','Request subscription activation'),('commercial.subscription.activate','Activate subscriptions created by another membership'),('commercial.subscription.suspend','Suspend subscriptions'),('commercial.subscription.resume','Resume subscriptions'),('commercial.subscription.cancel','Cancel subscriptions'),('commercial.subscription.terminate','Terminate subscriptions'),('commercial.subscription.renew','Renew subscriptions explicitly') ON CONFLICT(permission_key) DO NOTHING;
ALTER TABLE commercial.subscriptions ENABLE ROW LEVEL SECURITY; ALTER TABLE commercial.subscriptions FORCE ROW LEVEL SECURITY;
ALTER TABLE commercial.subscription_plan_origins ENABLE ROW LEVEL SECURITY; ALTER TABLE commercial.subscription_plan_origins FORCE ROW LEVEL SECURITY;
ALTER TABLE commercial.subscription_revisions ENABLE ROW LEVEL SECURITY; ALTER TABLE commercial.subscription_revisions FORCE ROW LEVEL SECURITY;
ALTER TABLE commercial.subscription_operations ENABLE ROW LEVEL SECURITY; ALTER TABLE commercial.subscription_operations FORCE ROW LEVEL SECURITY;
CREATE POLICY subscriptions_scope ON commercial.subscriptions FOR ALL USING (platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.read') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.create') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.update') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.assign') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.request_activation') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.activate') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.suspend') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.resume') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.cancel') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.terminate') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.renew')) WITH CHECK (platform.has_trusted_tenant_context(tenant_id,created_by,'commercial.subscription.create') OR platform.has_trusted_tenant_context(tenant_id,updated_by,'commercial.subscription.update') OR platform.has_trusted_tenant_context(tenant_id,updated_by,'commercial.subscription.assign') OR platform.has_trusted_tenant_context(tenant_id,updated_by,'commercial.subscription.request_activation') OR platform.has_trusted_tenant_context(tenant_id,updated_by,'commercial.subscription.activate') OR platform.has_trusted_tenant_context(tenant_id,updated_by,'commercial.subscription.suspend') OR platform.has_trusted_tenant_context(tenant_id,updated_by,'commercial.subscription.resume') OR platform.has_trusted_tenant_context(tenant_id,updated_by,'commercial.subscription.cancel') OR platform.has_trusted_tenant_context(tenant_id,updated_by,'commercial.subscription.terminate') OR platform.has_trusted_tenant_context(tenant_id,updated_by,'commercial.subscription.renew'));
CREATE POLICY subscription_origins_scope ON commercial.subscription_plan_origins FOR ALL USING (EXISTS(SELECT 1 FROM commercial.subscriptions s WHERE s.id=subscription_id AND s.tenant_id=subscription_plan_origins.tenant_id)) WITH CHECK (EXISTS(SELECT 1 FROM commercial.subscriptions s WHERE s.id=subscription_id AND s.tenant_id=subscription_plan_origins.tenant_id));
CREATE POLICY subscription_revisions_scope ON commercial.subscription_revisions FOR ALL USING (EXISTS(SELECT 1 FROM commercial.subscriptions s WHERE s.id=subscription_id AND s.tenant_id=subscription_revisions.tenant_id)) WITH CHECK (EXISTS(SELECT 1 FROM commercial.subscriptions s WHERE s.id=subscription_id AND s.tenant_id=subscription_revisions.tenant_id));
CREATE POLICY subscription_operations_scope ON commercial.subscription_operations FOR ALL USING(platform.has_trusted_tenant_context(tenant_id,NULL,operation)) WITH CHECK(platform.has_trusted_tenant_context(tenant_id,actor_user_id,operation));
CREATE POLICY subscription_contracts_read ON commercial.contracts FOR SELECT USING(platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.create') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.read') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.update') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.activate'));
CREATE POLICY subscription_contract_lines_read ON commercial.contract_line_items FOR SELECT USING(platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.create') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.read'));
CREATE POLICY subscription_memberships_read ON platform.memberships FOR SELECT USING(platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.create') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.assign') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.activate'));
CREATE POLICY audit_logs_subscription_insert ON platform.audit_logs FOR INSERT WITH CHECK(platform.has_trusted_tenant_context(tenant_id,actor_user_id,'commercial.subscription.create') OR platform.has_trusted_tenant_context(tenant_id,actor_user_id,'commercial.subscription.update') OR platform.has_trusted_tenant_context(tenant_id,actor_user_id,'commercial.subscription.assign') OR platform.has_trusted_tenant_context(tenant_id,actor_user_id,'commercial.subscription.request_activation') OR platform.has_trusted_tenant_context(tenant_id,actor_user_id,'commercial.subscription.activate') OR platform.has_trusted_tenant_context(tenant_id,actor_user_id,'commercial.subscription.suspend') OR platform.has_trusted_tenant_context(tenant_id,actor_user_id,'commercial.subscription.resume') OR platform.has_trusted_tenant_context(tenant_id,actor_user_id,'commercial.subscription.cancel') OR platform.has_trusted_tenant_context(tenant_id,actor_user_id,'commercial.subscription.terminate') OR platform.has_trusted_tenant_context(tenant_id,actor_user_id,'commercial.subscription.renew'));
CREATE POLICY domain_events_subscription_insert ON platform.domain_events FOR INSERT WITH CHECK(platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.create') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.update') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.assign') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.request_activation') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.activate') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.suspend') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.resume') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.cancel') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.terminate') OR platform.has_trusted_tenant_context(tenant_id,NULL,'commercial.subscription.renew'));
REVOKE ALL ON ALL TABLES IN SCHEMA commercial FROM PUBLIC;
GRANT USAGE ON SCHEMA commercial,platform TO acs_phase2_subscription_registry;
GRANT SELECT,INSERT,UPDATE ON commercial.subscriptions TO acs_phase2_subscription_registry;
GRANT SELECT,INSERT ON commercial.subscription_plan_origins,commercial.subscription_revisions,commercial.subscription_operations TO acs_phase2_subscription_registry;
GRANT SELECT ON commercial.contracts,commercial.contract_line_items,commercial.customers,platform.memberships TO acs_phase2_subscription_registry;
GRANT INSERT ON platform.audit_logs,platform.domain_events TO acs_phase2_subscription_registry;
GRANT EXECUTE ON FUNCTION platform.activate_tenant_context(uuid,text),platform.has_trusted_tenant_context(uuid,uuid,text) TO acs_phase2_subscription_registry;
COMMIT;
