BEGIN;
DELETE FROM platform.tenant_context_grants WHERE permission_key LIKE 'commercial.contract.%';
DELETE FROM platform.role_permissions WHERE permission_key LIKE 'commercial.contract.%';
DELETE FROM platform.membership_permissions WHERE permission_key LIKE 'commercial.contract.%';
DROP POLICY IF EXISTS domain_events_contract_insert ON platform.domain_events;
DROP POLICY IF EXISTS audit_logs_contract_insert ON platform.audit_logs;
DROP POLICY IF EXISTS contract_plans_read ON commercial.plans;
DROP POLICY IF EXISTS contract_partners_read ON commercial.partners;
DROP POLICY IF EXISTS contract_customers_read ON commercial.customers;
DROP POLICY IF EXISTS contract_opportunities_read ON commercial.opportunities;
DROP POLICY IF EXISTS contract_proposals_read ON commercial.proposals;
DROP POLICY IF EXISTS contract_memberships_read ON platform.memberships;
DROP TABLE IF EXISTS commercial.contract_operations;
DROP TABLE IF EXISTS commercial.contract_revision_line_items;
DROP TABLE IF EXISTS commercial.contract_revisions;
DROP TABLE IF EXISTS commercial.contract_line_items;
DROP TABLE IF EXISTS commercial.contracts;
DELETE FROM platform.permissions WHERE permission_key LIKE 'commercial.contract.%';
COMMIT;
