BEGIN;
DELETE FROM platform.tenant_context_grants WHERE permission_key LIKE 'commercial.subscription.%';
DELETE FROM platform.role_permissions WHERE permission_key LIKE 'commercial.subscription.%';
DELETE FROM platform.membership_permissions WHERE permission_key LIKE 'commercial.subscription.%';
DROP POLICY IF EXISTS domain_events_subscription_insert ON platform.domain_events;
DROP POLICY IF EXISTS audit_logs_subscription_insert ON platform.audit_logs;
DROP POLICY IF EXISTS subscription_memberships_read ON platform.memberships;
DROP POLICY IF EXISTS subscription_contract_lines_read ON commercial.contract_line_items;
DROP POLICY IF EXISTS subscription_contracts_read ON commercial.contracts;
DROP TABLE IF EXISTS commercial.subscription_operations;
DROP TABLE IF EXISTS commercial.subscription_revisions;
DROP TABLE IF EXISTS commercial.subscription_plan_origins;
DROP TABLE IF EXISTS commercial.subscriptions;
DELETE FROM platform.permissions WHERE permission_key LIKE 'commercial.subscription.%';
COMMIT;
