BEGIN;
DELETE FROM platform.tenant_context_grants WHERE permission_key LIKE 'commercial.rating.%';
DELETE FROM platform.role_permissions WHERE permission_key LIKE 'commercial.rating.%';
DELETE FROM platform.membership_permissions WHERE permission_key LIKE 'commercial.rating.%';
DELETE FROM platform.machine_principal_permissions WHERE permission_key LIKE 'commercial.rating.%';
DROP POLICY IF EXISTS rating_usage_read ON commercial.usage_aggregates;
DROP POLICY IF EXISTS rating_memberships_read ON platform.memberships;
DROP POLICY IF EXISTS audit_logs_rating_insert ON platform.audit_logs;
DROP POLICY IF EXISTS domain_events_rating_insert ON platform.domain_events;
DROP POLICY IF EXISTS rating_entitlements_read ON commercial.entitlements;
DROP POLICY IF EXISTS rating_subscriptions_read ON commercial.subscriptions;
DROP TABLE IF EXISTS commercial.rating_operations;
DROP TABLE IF EXISTS commercial.rated_facts;
DROP TABLE IF EXISTS commercial.rating_applicabilities;
DROP TABLE IF EXISTS commercial.rate_tiers;
DROP TABLE IF EXISTS commercial.rate_rules;
DROP TABLE IF EXISTS commercial.rate_plan_versions;
DROP TABLE IF EXISTS commercial.rate_plans;
DROP FUNCTION IF EXISTS commercial.rating_prevent_historical_mutation();
DROP FUNCTION IF EXISTS commercial.rating_prevent_rate_plan_version_overlap();
DROP FUNCTION IF EXISTS commercial.rating_prevent_applicability_overlap();
DROP FUNCTION IF EXISTS commercial.rating_prevent_tier_overlap();
DELETE FROM platform.permissions WHERE permission_key LIKE 'commercial.rating.%';
COMMIT;
